### ISSUE TITLE
Pose causes test suite to fail

### ISSUE THREAD

**Issue by marcaaron** [Popmotion/popmotion#422]
Have others experienced this? Using react-native-pose.

```
FAIL  App/App.test.js
  ● Test suite failed to run

    /home/circleci/repo/node_modules/react-pose-core/lib/posed.js:20
                return !withParent || props.parentValues ? (<PoseComponent_1.PoseComponent poseConfig={poseConfig} factoryConfig={factoryConfig} Component={Component} {...props}/>) : (<PoseComponent_1.PoseParentContext.Consumer>
                                                            ^
    
    SyntaxError: Unexpected token <
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
      at Object.<anonymous> (node_modules/react-pose-core/lib/index.js:3:15)
      at Object.<anonymous> (node_modules/react-native-pose/lib/index.js:1:697)

Test Suites: 1 failed, 10 passed, 11 total
```

**App.test.js**
```
import App from './index';
import { createSnapshot } from '../src/util/tests';

describe('App', () => {
  it('renders without crashing', () => {
    const snapshot = createSnapshot(App);
    expect(snapshot).toMatchSnapshot();
  });
});
```
**src/util/tests**
```
import React from 'react';
import ShallowRenderer from 'react-test-renderer/shallow';

export const createSnapshot = (Component, props) => {
  const renderer = new ShallowRenderer();
  renderer.render(<Component {...props} />);
  return renderer.getRenderOutput();
};
```

**Comment by InventingWithMonster** [comment]
It’s weird looks like the JSX isn’t being correctly transpiled. I’ll be able to take a look in about an hour

**Comment by InventingWithMonster** [comment]
Ah yeah this is by design. React Native expects to consume external modules with JSX still present, so `react-pose-core` is using the `'react-native'` JSX transpilation configuration.

Have you set 
```
  "jest": {
    "preset": "react-native"
  }
```

In your `package.json`?

**Comment by marcaaron** [comment]
We're using the "jest-expo" preset that comes with create-react-native-app. Just tried a fresh CRNA install with react-native-pose added. Importing posed from react-native-pose into App.js will cause this same error.

As per some suggestions I saw floating around I did add the following to the jest options in package.json which seems to have fixed this particular issue. Although I must admit I'm not entirely sure why. 

```
    "transformIgnorePatterns": [
      "node_modules/(?!react-native|react-pose-core)"
    ]
```

**Comment by InventingWithMonster** [comment]
That’s odd. What version are you using

**Comment by marcaaron** [comment]
```
{
  ...
  "devDependencies": {
    "babel-eslint": "^8.2.5",
    "eslint": "^4.19.1",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-native": "^3.2.1",
    "firebase-mock": "^2.2.4",
    "jest-expo": "~27.0.0",
    "react-native-scripts": "1.14.0",
    "react-test-renderer": "16.3.1"
  },
  ...
  "jest": {
    "preset": "jest-expo",
    "setupFiles": [
      "./testConfig/jestConfig.js"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!react-navigation|react-native|react-native-pose|react-pose-core)"
    ]
  },
  "dependencies": {
    "expo": "^27.0.2",
    "firebase": "^5.0.4",
    "prop-types": "^15.6.2",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-elements": "^0.19.1",
    "react-native-pose": "^0.3.0",
    "react-native-snap-carousel": "^3.7.2",
    "react-navigation": "^2.5.5",
    "react-redux": "^5.0.7",
    "recompose": "^0.27.1",
    "redux": "^4.0.0",
    "redux-saga": "^0.16.0"
  }
}
```
